import { SITE_URL } from "@/lib/constants";
import { MetadataRoute } from "next";

/**
 * robots.txt generated by Next.js at /robots.txt.
 * Allows all crawlers, blocks admin routes, and points to sitemap.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/admin/", "/api/"],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
  };
}
